### ISSUE TITLE
About the function prepare_file()

### ISSUE THREAD

**Issue by taotianli** [mabhijithn/irregulars-neureka-codebase#2]
I have a question about the code in the file in train/4-train-lstm.py

When you define the function, the function just return x, which refers to the three pre-computed prediction. However, in the function train(), you use the function prepare_file() to return x & y. What does y stand for? I guess y stands for reference file, right?

**Comment by mabhijithn** [comment]
The commits and merge 1512188f25ff4682ba04d486d766ec201ce82c8d fixes the issue. Thanks @taotianli .
