### ISSUE TITLE
OS module function in 4-train-lstm.py file in training folder typo

### ISSUE THREAD

**Issue by sgopalan98** [mabhijithn/irregulars-neureka-codebase#4]
Congrats on achieving a great score!! The presentation was really good and gave us a lot of insights. Thanks for that! :D

In Line no:
https://github.com/mabhijithn/irregulars-neureka-codebase/blob/ef0fdafc5ee94dc54cb496971cec857958f57c3c/training/4-train-lstm.py#L31

The function used here is os.joind.  However, there are no functions like joind in the os module. Should it be os.path.join?

Also, the open issue : https://github.com/mabhijithn/irregulars-neureka-codebase/issues/2, where input and output doesn't exactly match?

**Comment by mabhijithn** [comment]
Resolved by 1512188f25ff4682ba04d486d766ec201ce82c8d
