### ISSUE TITLE
Just a question about the specs of the system used to train the models

### ISSUE THREAD

**Issue by MuSamiNaf** [mabhijithn/irregulars-neureka-codebase#6]
Thanks for your great work and contribution to the EEG analysis society.

I am interested to know the specs of the system used to train the model. Clock Speed, RAM, HDD disk space, GPU (in case it was used), etc..

Also, what was the average time to train the model on the whole train dataset?

Thank you

**Comment by nseeuws** [comment]
Thanks for the nice words!

We trained our models on a variety of systems, so it's difficult to give 1 precise answer. The full dataset for a single view (in EDF format) needed around 60GB of disk space, the actual signals (single precision) in memory were around 45GB.

Training a U-net on a single view (the heaviest GPU load) took around 20 hours on a single RTX 2080. (on a machine with 64GB of RAM and a recent 6 core i7 cpu)

Hope this helps!
