### ISSUE TITLE
About Python installation package version problem and data set

### ISSUE THREAD

**Issue by user-yifanjiang** [mabhijithn/irregulars-neureka-codebase#7]
Thank you for your contribution to EEG.
I'm new to this,when i run your code ,i have a lot of version issues,so i want to know all the versions that you list in the python_requirement.txt.
I also want to know how to download the dataset 
![1](https://user-images.githubusercontent.com/73929581/120162033-90e0d200-c22a-11eb-8b4e-07e58beae36b.png)
I am looking forward to your early reply,thanks.

**Comment by HarperShi** [comment]
> Thank you for your contribution to EEG.
> I'm new to this,when i run your code ,i have a lot of version issues,so i want to know all the versions that you list in the python_requirement.txt.
> I also want to know how to download the dataset
> ![1](https://user-images.githubusercontent.com/73929581/120162033-90e0d200-c22a-11eb-8b4e-07e58beae36b.png)
> I am looking forward to your early reply,thanks.

Hello, Yifan, I'm also a new starter to this project and have a few questions about it. I was wondering if we could talk about them together? My email address is harpersxn@gmail.com. Hope for your reply

**Comment by mabhijithn** [comment]
Versions have been added with this [commit](https://github.com/mabhijithn/irregulars-neureka-codebase/pull/8).
Yet to fully test it. Feel free to let us know if these versions help you.
You need to fill out this [form](https://www.isip.piconepress.com/projects/tuh_eeg/html/request_access.php) to get username and password to download TUSZ corpus. After you get this, look at the [instructions](https://www.isip.piconepress.com/projects/tuh_eeg/html/downloads.shtml#inst) on how to download the corpus.
